### ISSUE TITLE
docs: add/modify specs to describe auction types

### ISSUE THREAD

**Issue by jeonghoyeo7** [tendermint/fundraising#84]
## Summary
This is to add and modify the spec documents to describe auction types of fixed price auction and batch auction.

## Tasks

- [ ] Draft 01_concept.md

- [ ] Draft 02_state.md

- [ ] Draft 03_state_transitions.md

- [ ] Draft 04_messages.md 

- [ ] Draft 05_end_block.md

- [ ] Draft 06_events.md

- [ ] Draft 07_params.md

- [ ] Clarify the explanations

- [ ] Modify the related proto files to define the states

## References
- Continued work from https://github.com/tendermint/fundraising/issues/81
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
